# Generated by Django 2.2.2 on 2020-09-04 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funclapi', '0002_family_seven'),
    ]

    operations = [
        migrations.DeleteModel(
            name='family',
        ),
        migrations.DeleteModel(
            name='seven',
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
