# Generated by Django 2.2.2 on 2020-09-04 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funclapi', '0005_auto_20200904_2106'),
    ]

    operations = [
        migrations.DeleteModel(
            name='seven',
        ),
        migrations.DeleteModel(
            name='user',
        ),
        migrations.DeleteModel(
            name='wefamily',
        ),
    ]
