# Generated by Django 2.2.2 on 2020-09-04 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funclapi', '0007_family'),
    ]

    operations = [
        migrations.DeleteModel(
            name='family',
        ),
    ]
