# Generated by Django 2.2.2 on 2020-09-04 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funclapi', '0009_seven_user_wefamily'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
