# Generated by Django 2.2.2 on 2020-10-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funclapi', '0011_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='seven',
            name='picture',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tdee',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wefamily',
            name='picture',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='seven',
            name='calories',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='seven',
            name='items',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='bmr',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wefamily',
            name='calories',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wefamily',
            name='carbohydrate',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wefamily',
            name='fat',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wefamily',
            name='items',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wefamily',
            name='perserving',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wefamily',
            name='protein',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wefamily',
            name='saturatedfat',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wefamily',
            name='sodium',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wefamily',
            name='sugar',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wefamily',
            name='transfat',
            field=models.CharField(max_length=100),
        ),
    ]
