# Generated by Django 2.2.2 on 2020-10-05 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funclapi', '0012_auto_20201005_2221'),
    ]

    operations = [
        migrations.DeleteModel(
            name='seven',
        ),
        migrations.DeleteModel(
            name='user',
        ),
        migrations.DeleteModel(
            name='wefamily',
        ),
    ]
