# Generated by Django 2.2.2 on 2020-10-14 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funclapi', '0016_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
