# Generated by Django 2.2.2 on 2020-10-14 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funclapi', '0017_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='users',
        ),
    ]
