# Generated by Django 2.2.2 on 2020-10-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funclapi', '0020_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('bmr', models.CharField(max_length=100)),
                ('tdee', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
