# Generated by Django 2.2.2 on 2020-10-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funclapi', '0021_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('uid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('height', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('bmr', models.CharField(max_length=100)),
                ('tdee', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
