# Generated by Django 2.2.2 on 2020-10-25 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funclapi', '0022_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=250)),
                ('calories', models.CharField(max_length=100)),
                ('picture', models.CharField(max_length=250, null=True)),
                ('convenience', models.CharField(max_length=100)),
                ('kind', models.CharField(max_length=100)),
            ],
        ),
    ]
