# Generated by Django 2.2.2 on 2020-11-01 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funclapi', '0024_eat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='eat',
        ),
    ]
