# Generated by Django 2.2.2 on 2020-11-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funclapi', '0025_delete_eat'),
    ]

    operations = [
        migrations.CreateModel(
            name='eat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100)),
                ('bmr', models.CharField(max_length=100)),
                ('tdee', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('items', models.CharField(max_length=250)),
                ('calories', models.CharField(max_length=100)),
            ],
        ),
    ]
