# Generated by Django 2.2.2 on 2020-11-02 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funclapi', '0026_eat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='eat',
        ),
    ]
