# Generated by Django 2.2.2 on 2020-11-02 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funclapi', '0028_eat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='eat',
        ),
    ]
