# Generated by Django 2.2.2 on 2020-11-04 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funclapi', '0031_daily'),
    ]

    operations = [
        migrations.DeleteModel(
            name='eat',
        ),
        migrations.DeleteModel(
            name='food',
        ),
    ]
