# Generated by Django 2.2.2 on 2020-11-04 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funclapi', '0033_eat_food'),
    ]

    operations = [
        migrations.DeleteModel(
            name='eat',
        ),
        migrations.DeleteModel(
            name='food',
        ),
    ]
