# Generated by Django 2.2.2 on 2020-11-09 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funclapi', '0035_eat_food'),
    ]

    operations = [
        migrations.DeleteModel(
            name='daily',
        ),
        migrations.DeleteModel(
            name='seven',
        ),
        migrations.DeleteModel(
            name='users',
        ),
    ]
