# Generated by Django 2.2.2 on 2020-11-09 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funclapi', '0036_auto_20201109_1315'),
    ]

    operations = [
        migrations.DeleteModel(
            name='eat',
        ),
    ]
