# Generated by Django 2.2.2 on 2020-11-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funclapi', '0037_delete_eat'),
    ]

    operations = [
        migrations.CreateModel(
            name='eat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100)),
                ('bmr', models.CharField(max_length=100)),
                ('tdee', models.CharField(max_length=100)),
                ('datetime', models.CharField(max_length=100)),
                ('items', models.CharField(max_length=250)),
                ('calories', models.DecimalField(decimal_places=1, max_digits=10)),
                ('total', models.DecimalField(decimal_places=1, max_digits=10)),
                ('times', models.IntegerField(default=0)),
            ],
        ),
    ]
