# Generated by Django 2.2.2 on 2020-11-09 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funclapi', '0038_eat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='eat',
        ),
    ]
