# Generated by Django 2.2.2 on 2020-11-17 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funclapi', '0040_eat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='eat',
        ),
        migrations.DeleteModel(
            name='food',
        ),
    ]
